import {Center} from 'center'
var centers: Center[] = [

    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Irbid",
        vaccines: ["Senopharm", 'Pfizer'],
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 2, 
        namecenters: 'ramtha education',
        city:"Irbid",
        distance: 10, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location: 'university Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-1pm",
        requirdappointment:true,
    },
    {
        id: 3, 
        namecenters: 'King Hussein',
        city:"Amman", 
        vaccines: ["Senopharm", 'astrazeneca'],
        location : 'Alshohda Street',
        firstDose: true,
        secondDose: true,
        distance: 15, 
        requirdappointment:true,
        workingtime:"8am-3pm",
        latittude: 31.99,
        longitude:35.99,
        
        
    },
    {
        id: 4, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'Gym city',
        vaccines: ["Senopharm"],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 5, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'Alnaser Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 6, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'wadi alseer',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    },
    {
        id: 1, 
        namecenters: 'King Hussein',
        city:"Amman",
        distance: 15, 
        firstDose: true,
        secondDose: true,
        latittude: 31.99,
        longitude:35.99,
        location : 'AlHoreya Street',
        vaccines: ["Senopharm", 'Pfizer'],
        workingtime:"8am-3pm",
        requirdappointment:true,
    }

];

export default centers;